settings:
  hostname: ""
  RTCPP: 12580
  RUDPP: 12581
  isContinuity: false
  mixture: true
  step: 600
  dataSizeMB: 100
  mysqlAddress: 0HpNlDeO70YTFJxYX7k5qlPpYgtsR1o/25F4MmoLTOw=
  mysqlPassWord: F5BM56YG+SoN4wm0Wo5Mzw==
  useDB: false
  mysqlUser: root
points:
- address: 142.93.130.140
  alias: Digital_Ocean_Amsterdam
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 43.245.198.188
  alias: GIGS_Singapore
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 118.25.222.57
  alias: TX_ChengDu1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 118.193.92.99
  alias: SDZX_Tokyo
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 47.95.13.35
  alias: Ali_HuaBei2_Beijing2
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 178.128.19.76
  alias: Digital_Ocean_Singapore
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 45.79.236.179
  alias: Linode_Sydney
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 8.208.99.95
  alias: Ali_London
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 47.74.5.6
  alias: Ali_TK1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 178.62.63.32
  alias: Digital_Ocean_London
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 117.78.40.125
  alias: HuaWei_BJ1_1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 74.207.247.229
  alias: Linode_Fremont
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 39.104.157.114
  alias: Ali_HuHeHaoTe3
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 47.92.136.106
  alias: Ali_HuaBei3
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 8.135.5.227
  alias: Ali_HuaNan1_ShenZhen
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 139.162.206.97
  alias: Linode_London
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 118.193.95.130
  alias: SDZX_HK
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 119.28.132.215
  alias: TX_HK1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 47.254.245.252
  alias: Ali_KualaLumpur
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 172.104.234.14
  alias: Linode_Frankfurt
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 119.45.32.178
  alias: TX_Nanjing1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 159.138.29.204
  alias: HuaWei_HK1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 119.3.66.99
  alias: HuaWei_Shanghai2_1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 103.228.162.74
  alias: SDZX_GuangZhou
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 163.53.169.226
  alias: SDZX_WuXi
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 49.51.36.183
  alias: TX_Silicon_Valley3
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 8.131.51.195
  alias: Ali_HuaBei2_Beijing1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 39.105.155.239
  alias: Ali_HuaBei2_Beijing3
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 117.78.40.174
  alias: HuaWei_BJ1_2
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 119.28.162.23
  alias: TX_Seoul1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 212.64.36.15
  alias: TX_Shanghai3
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 150.109.198.133
  alias: TX_Tokyo1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 164.52.43.242
  alias: SDZX_Korea
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 118.193.92.98
  alias: SDZX_Tokyo_Extranet
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 140.143.194.72
  alias: TX_BJ4
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 172.105.16.142
  alias: Linode_Toronto
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 103.228.162.75
  alias: SDZX_GuangZhou_Extranet
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 101.89.68.11
  alias: SDZX_ShangHai_Extranet
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 162.62.21.95
  alias: TX_Moscow1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 39.104.209.234
  alias: Ali_HuHeHaoTe1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 134.209.53.210
  alias: Digital_Ocean_San_Francisco
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 139.162.124.245
  alias: Linode_Tokyo
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 43.245.223.31
  alias: GIGS_HK
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 148.153.55.35
  alias: SDZX_Dallas_Extranet
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 148.153.44.210
  alias: SDZX_LA
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 163.53.169.227
  alias: SDZX_WuXi_Extranet
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 140.143.95.113
  alias: TX_ChengDu2
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 47.91.108.180
  alias: Ali_Dubai
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 47.88.223.188
  alias: Ali_Singapore1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 122.152.204.30
  alias: TX_Shanghai2
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 129.211.100.53
  alias: TX_Shanghai4
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 150.109.46.26
  alias: TX_HK2
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 49.51.51.111
  alias: TX_SiliconValley1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 119.28.113.54
  alias: TX_Singapore1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 139.9.4.193
  alias: HuaWei_GuangZhou1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 148.153.25.138
  alias: SDZX_Amsterdam
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 164.52.11.42
  alias: SDZX_TaiWan
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 139.9.7.213
  alias: HuaWei_GuangZhou3
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 139.162.99.77
  alias: Linode_Tokyo2_2
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 164.52.11.43
  alias: SDZX_TaiWan_Extranet
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 154.8.157.226
  alias: TX_BJ2
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 150.109.180.71
  alias: TX_Bangkon1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 47.91.77.39
  alias: Ali_Frankfurt
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 47.254.17.3
  alias: Ali_SiliconValley
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 139.9.0.76
  alias: HuaWei_GuangZhou2
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 124.156.17.225
  alias: TX_Mumbai1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 62.234.132.63
  alias: TX_BJ3
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 118.24.249.139
  alias: TX_ChongQin1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 157.230.233.63
  alias: Digital_Ocean_New_York
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 159.138.27.74
  alias: HuaWei_HK2
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 148.153.44.211
  alias: SDZX_LA_Extranet
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 164.52.43.243
  alias: SDZX_Korea_Extranet
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 116.62.78.247
  alias: Ali_HuaDong1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 68.183.71.22
  alias: Digital_Ocean_Frankfurt
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 49.4.95.24
  alias: HuaWei_BJ1_3
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 173.255.227.93
  alias: Linode_Newwark
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 172.105.121.219
  alias: Linode_Singapore
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 148.153.25.139
  alias: SDZX_Amsterdam_Extranet
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 106.3.133.2
  alias: SDZX_BJ
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 118.193.95.131
  alias: SDZX_HK_Extranet
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 147.139.168.149
  alias: Ali_Jakarta
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 47.91.41.14
  alias: Ali_Sydney
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 119.3.74.239
  alias: HuaWei_Shanghai2_2
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 150.109.186.240
  alias: TX_Bangkok2
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 49.51.132.138
  alias: TX_Frankfurt1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 49.51.81.235
  alias: TX_Virginia1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 148.153.55.34
  alias: SDZX_Dallas
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 138.197.151.249
  alias: Digital_Ocean_Toronto
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 119.3.68.133
  alias: HuaWei_Shanghai2_3
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 49.51.10.150
  alias: TX_Toronto1
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 106.15.190.245
  alias: Ali_HuaDong2
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 47.90.201.151
  alias: Ali_Virginia
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 47.108.51.129
  alias: Ali_XiNan1_ChengDu
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 164.52.88.2
  alias: SDZX_Singapore
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 164.52.88.3
  alias: SDZX_Singapore_Extranet
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 162.62.16.30
  alias: TX_Moscow2
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 49.51.200.157
  alias: TX_SiliconValley2
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 39.104.227.118
  alias: Ali_HuHeHaoTe2
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 149.129.130.238
  alias: Ali_bombay
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
- address: 45.79.57.238
  alias: Linode_Dalas
  periodPacketNum: 50
  perPacketIntervalMs: 10
  perPacketIntervalUs: 0
  periodNum: 1
  periodMs: 0
  size: 64
